### ISSUE TITLE
question about your code

### ISSUE THREAD

**Issue by xilinniao123** [TanyaZhao/MRC4ERE_plus#3]
thanks for sharing! but one quesiton  about your code mrc_utils.py
![image](https://user-images.githubusercontent.com/11830865/89728374-7a7d4600-da5f-11ea-8272-d68efed1640c.png)

your labels is only consider doc tokens not conside question? this may be wrong??

**Comment by TanyaZhao** [comment]
Yes. We don't consider the label of questions. The sequence labeling is only for context tokens.
