### ISSUE TITLE
求模型文件

### ISSUE THREAD

**Issue by XinyanLi2016** [TanyaZhao/MRC4ERE_plus#5]
学姐你好，最近读了您的论文发现其中思想很不错。想继续深入拜读一下您的代码，但是在运行的时候发现没有模型文件，请问可以发布一下吗？或者如果您方便的话私发至我的邮箱1024393147@qq.com，期待学姐的回复，感谢！祝您科研工作顺利！

**Comment by TanyaZhao** [comment]
We have updated the model part.
